version: "3.8"

services:
  app:
    build: .
    container_name: go-app
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - db 
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_SCHEEMA} 
      MYSQL_USER: ${DB_USERNAME} 
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "53306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql 

volumes:
  mysql-data:
